-- MySQL Script generated by MySQL Workbench
-- Sat May  4 12:13:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lxp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lxp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lxp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lxp` ;

-- -----------------------------------------------------
-- Table `lxp`.`course_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`course_category` (
  `catagory_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `category` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`catagory_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`course_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`course_levels` (
  `level_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `level` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`level_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`course` (
  `course_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `level_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `catagory_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `title` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `duration` DECIMAL(65,30) NOT NULL,
  `thumbnail` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `is_available` TINYINT(1) NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `IX_course_catagory_id` (`catagory_id` ASC) VISIBLE,
  INDEX `IX_course_level_id` (`level_id` ASC) VISIBLE,
  CONSTRAINT `FK_course_course_category_catagory_id`
    FOREIGN KEY (`catagory_id`)
    REFERENCES `lxp`.`course_category` (`catagory_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_course_course_levels_level_id`
    FOREIGN KEY (`level_id`)
    REFERENCES `lxp`.`course_levels` (`level_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`learners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`learners` (
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `password` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `role` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `unblock_request` TINYINT(1) NOT NULL,
  `account_status` TINYINT(1) NOT NULL,
  `user_last_login` DATETIME NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`learner_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`enrollments` (
  `enrollment_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `course_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `enrollment_date` DATETIME NOT NULL,
  `enroll_status` TINYINT(1) NOT NULL,
  `enroll_request_status` TINYINT(1) NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `IX_enrollments_course_id` (`course_id` ASC) VISIBLE,
  INDEX `IX_enrollments_learner_id` (`learner_id` ASC) VISIBLE,
  CONSTRAINT `FK_enrollments_course_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `lxp`.`course` (`course_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_enrollments_learners_learner_id`
    FOREIGN KEY (`learner_id`)
    REFERENCES `lxp`.`learners` (`learner_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`topic` (
  `topic_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `course_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`topic_id`),
  INDEX `IX_topic_course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `FK_topic_course_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `lxp`.`course` (`course_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`feedback_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`feedback_questions` (
  `feedback_question_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `topic_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `question_no` INT NOT NULL,
  `question` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `question_type` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `feedback_type` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`feedback_question_id`),
  INDEX `IX_feedback_questions_topic_id` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `FK_feedback_questions_topic_topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `lxp`.`topic` (`topic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`feedback_question_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`feedback_question_options` (
  `option_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `feedback_question_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `option` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`option_id`),
  INDEX `IX_feedback_question_options_feedback_question_id` (`feedback_question_id` ASC) VISIBLE,
  CONSTRAINT `FK_feedback_question_options_feedback_questions_feedback_questi~`
    FOREIGN KEY (`feedback_question_id`)
    REFERENCES `lxp`.`feedback_questions` (`feedback_question_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`feedback_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`feedback_responses` (
  `feedback_response_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `feedback_question_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `response` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `feedback_question_optionoption_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`feedback_response_id`),
  INDEX `IX_feedback_responses_feedback_question_id` (`feedback_question_id` ASC) VISIBLE,
  INDEX `IX_feedback_responses_feedback_question_optionoption_id` (`feedback_question_optionoption_id` ASC) VISIBLE,
  INDEX `IX_feedback_responses_learner_id` (`learner_id` ASC) VISIBLE,
  CONSTRAINT `FK_feedback_responses_feedback_question_options_feedback_questi~`
    FOREIGN KEY (`feedback_question_optionoption_id`)
    REFERENCES `lxp`.`feedback_question_options` (`option_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_feedback_responses_feedback_questions_feedback_question_id`
    FOREIGN KEY (`feedback_question_id`)
    REFERENCES `lxp`.`feedback_questions` (`feedback_question_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_feedback_responses_learners_learner_id`
    FOREIGN KEY (`learner_id`)
    REFERENCES `lxp`.`learners` (`learner_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`quizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`quizzes` (
  `quiz_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `course_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `topic_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `name_of_quiz` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `duration` INT NOT NULL,
  `pass_mark` INT NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`quiz_id`),
  UNIQUE INDEX `topic_id_UNIQUE` (`topic_id` ASC) VISIBLE,
  INDEX `IX_quizzes_course_id` (`course_id` ASC) VISIBLE,
  INDEX `IX_quizzes_topic_id` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `FK_quizzes_course_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `lxp`.`course` (`course_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_quizzes_topic_topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `lxp`.`topic` (`topic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`learner_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`learner_attempts` (
  `learner_attempt_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `quiz_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `attempt_count` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `score` FLOAT NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`learner_attempt_id`),
  INDEX `IX_learner_attempts_learner_id` (`learner_id` ASC) VISIBLE,
  INDEX `IX_learner_attempts_quiz_id` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `FK_learner_attempts_learners_learner_id`
    FOREIGN KEY (`learner_id`)
    REFERENCES `lxp`.`learners` (`learner_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_learner_attempts_quizzes_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `lxp`.`quizzes` (`quiz_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`quiz_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`quiz_questions` (
  `quiz_question_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `quiz_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `question_no` INT NOT NULL,
  `question` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `question_type` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`quiz_question_id`),
  INDEX `IX_quiz_questions_quiz_id` (`quiz_id` ASC) VISIBLE,
  CONSTRAINT `FK_quiz_questions_quizzes_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `lxp`.`quizzes` (`quiz_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`question_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`question_options` (
  `question_option_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `quiz_question_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `option` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `is_correct` TINYINT(1) NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`question_option_id`),
  INDEX `IX_question_options_quiz_question_id` (`quiz_question_id` ASC) VISIBLE,
  CONSTRAINT `FK_question_options_quiz_questions_quiz_question_id`
    FOREIGN KEY (`quiz_question_id`)
    REFERENCES `lxp`.`quiz_questions` (`quiz_question_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`learner_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`learner_answers` (
  `learner_answer_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `learner_attempt_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `quiz_question_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `question_option_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`learner_answer_id`),
  INDEX `IX_learner_answers_learner_attempt_id` (`learner_attempt_id` ASC) VISIBLE,
  INDEX `IX_learner_answers_question_option_id` (`question_option_id` ASC) VISIBLE,
  INDEX `IX_learner_answers_quiz_question_id` (`quiz_question_id` ASC) VISIBLE,
  CONSTRAINT `FK_learner_answers_learner_attempts_learner_attempt_id`
    FOREIGN KEY (`learner_attempt_id`)
    REFERENCES `lxp`.`learner_attempts` (`learner_attempt_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_learner_answers_question_options_question_option_id`
    FOREIGN KEY (`question_option_id`)
    REFERENCES `lxp`.`question_options` (`question_option_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_learner_answers_quiz_questions_quiz_question_id`
    FOREIGN KEY (`quiz_question_id`)
    REFERENCES `lxp`.`quiz_questions` (`quiz_question_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`learner_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`learner_profiles` (
  `profile_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `first_name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `last_name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `dob` DATE NOT NULL,
  `gender` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `contact_number` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `stream` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `profile_photo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`profile_id`),
  INDEX `IX_learner_profiles_learner_id` (`learner_id` ASC) VISIBLE,
  CONSTRAINT `FK_learner_profiles_learners_learner_id`
    FOREIGN KEY (`learner_id`)
    REFERENCES `lxp`.`learners` (`learner_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`material_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`material_types` (
  `material_type_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `type` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`material_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`materials` (
  `material_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `topic_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `material_type_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `file_path` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `duration` DECIMAL(65,30) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `is_available` TINYINT(1) NOT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`material_id`),
  INDEX `IX_materials_material_type_id` (`material_type_id` ASC) VISIBLE,
  INDEX `IX_materials_topic_id` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `FK_materials_material_types_material_type_id`
    FOREIGN KEY (`material_type_id`)
    REFERENCES `lxp`.`material_types` (`material_type_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_materials_topic_topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `lxp`.`topic` (`topic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`learner_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`learner_progress` (
  `learner_progress_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `course_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `topic_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `material_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `watch_time` TIME NOT NULL,
  `total_time` TIME NOT NULL,
  `is_watched` TINYINT(1) NOT NULL,
  PRIMARY KEY (`learner_progress_id`),
  INDEX `IX_learner_progress_course_id` (`course_id` ASC) VISIBLE,
  INDEX `IX_learner_progress_learner_id` (`learner_id` ASC) VISIBLE,
  INDEX `IX_learner_progress_material_id` (`material_id` ASC) VISIBLE,
  INDEX `IX_learner_progress_topic_id` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `FK_learner_progress_course_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `lxp`.`course` (`course_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_learner_progress_learners_learner_id`
    FOREIGN KEY (`learner_id`)
    REFERENCES `lxp`.`learners` (`learner_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_learner_progress_materials_material_id`
    FOREIGN KEY (`material_id`)
    REFERENCES `lxp`.`materials` (`material_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_learner_progress_topic_topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `lxp`.`topic` (`topic_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lxp`.`password_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lxp`.`password_histories` (
  `password_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `learner_id` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `old_password` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `new_password` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `created_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_by` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `modified_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`password_id`),
  INDEX `IX_password_histories_learner_id` (`learner_id` ASC) VISIBLE,
  CONSTRAINT `FK_password_histories_learners_learner_id`
    FOREIGN KEY (`learner_id`)
    REFERENCES `lxp`.`learners` (`learner_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
